channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.1
  - lz4==4.4.4
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
